# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/hello/User
Accept: application/json

###

POST http://127.0.0.1:8000/book/add
Content-Type: application/json

{
  "bookname": "测试书籍",
  "author": "测试作者",
  "price": 99.99,
  "publisher": "测试出版社"
}

###

GET http://127.0.0.1:8000/book/books
Accept: application/json

###
