# Test your FastAPI endpoints

GET http://127.0.0.1:8000/
Accept: application/json

###

GET http://127.0.0.1:8000/book/100
Accept: application/json

###

GET http://127.0.0.1:8000/new/new_list?skip=0&limit=10
Accept: application/json

###

POST http://127.0.0.1:8000/register
Accept: application/json
Content-Type: application/json

{
  "username": "dbw",
  "password": "123456"
}

###